# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rj-s02vkM3_r2zioy1NqD4vvC_mbb1kK
"""

nama = input("Nama: ")
kelas = input("Kelas: ")
nim = input("NIM: ")
a = float(input("Masukan nilai kuis 1: "))
b = float(input("Masukan nilai kuis 2: "))
c = float(input("Masukan nilai kuis 3: "))
hasil = (a+b+c)/3
print("Rata-rata Kuis : ",(hasil))

print("=====Program Konversi Suhu=====")

reamur = int(input("Masukkan nilai Reamur : "));
celcius = (5 / 4) * reamur;
fahrenheit = (9 / 4) * reamur + 32;
kelvin = (5 / 4) * reamur + 273;
# KONVERSI REAMUR

print(reamur,"Reamur ke Celcius : ", celcius, "C");
print("Reamur ke Fahrenheit :", fahrenheit, "F");
print("Reamur ke Kelvin :", kelvin, "K");

n = int(input("Banyaknya Data: \n saya"))

print() #Membuat baris baru
data = []
jum = 0

for i in range(0, n):
    temp = int(input("Masukkan data ke-%d: " % (i+1)))
    data.append(temp)
    jum += data[i]
    rata2 = jum / n

print("\nRata-rata  = %0.2f" % rata2)