# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KE8eQfOBWSHIdiaF4moueEMiaUOsvE07
"""

a= ['saya', 12 ,'kamu', 'dia', 1, 10]
b, c, d, e, f, g = a
print (d)
for i in range (4):
  print(i*2)

if 5>3:
  print ('true')

misal="aku cantik"
print(misal[0:5])

x=5
y=10
z= x+y
print(z)

b = "amel"
b = 2
print(b)

x = str(3)    # x will be '3'
y = int(3)    # y will be 3
z = float(3/4)  # z will be 3.0
print (z)

#Variable names are case-sensitive (age, Age and AGE are three different variables)
myVariableName = "mel" #camel case (Each word, except the first, starts with a capital letter)
MyVariableName = "mil" #pascal case (Each word starts with a capital letter)
my_variable_name = "gat" #snake case (Each word is separated by an underscore character)

x, y, z = "Orange", "Banana", "Cherry" #Many Values to Multiple Variables
print(x)

x = y = z = "Orange" #One Value to Multiple Variables
print(x)

fruits = ["apple", "banana", "cherry"] #Unpack a Collection
x, y, z = fruits
print(z)

#If you try to combine a string and a number, Python will give you an error
x = "Python is " 
y = "awesome"
z =  x + y
print(z)

"""scope global function"""

x = "awesome"

def myfunc():
  x = "fantastic"
  print("Python is " + x)

myfunc()
def myfunc():
  x = "fantastic"
  print("my " + x)
myfunc()

print("Python is " + x)
print("our " + x)

x = "awesome"

def myfunc():
  print("Python is " + x)
myfunc()

x = "hore"
def myfunc():
  global x
  x="wow"
myfunc()
print("libur ini " + x)

m = 10 #global function
def oke(): #local function
  m= 15
  print("inside func", m)
oke()
print("outside func", m)

m = 10 #global function
def oke(): #local function
  global m
  m= 15
  print("inside func", m)
oke()
print("outside func", m)

m = 10
print (id(m))
def oke(): 
  m= 15

  x= globals()['m']
  print (id(x))
  print("inside func", m)

  globals () ['m']=20
oke()
print("outside func", m)

a = 0 #not use global

def one():
  a = 2
  
  def two():
    a = 4
    print(a)

  two()
  print(a)

one()
print (a)

def rose(x):
  return x * 10
hasil= rose(10)
print(hasil)

bilangan1= input("bilangan 1= ")
bilangan2= input("bilangan 2= ")
def max(a,b):
   if (int (a>b)):
      return a
   else:
      return b
print("nilai max adalah " + max(bilangan1, bilangan2))

bilangan = input('Masukan bilangan: ')

if (int (bilangan) % 2 == 0):
    print ("hasil merupakan bilangan genap")
else:
    print ("hasil merupakan bilangan ganjil")